services:
  - type: web
    name: choblog-8-mission
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    disk:
      name: renderup-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /var/data
      - key: MASTER_CODE
        sync: false
